api = "0.10"

[buildpack]
  description = "A Cloud Native Buildpack that provides the UPX binary compression tool"
  homepage = "https://github.com/paketo-buildpacks/upx"
  id = "paketo-buildpacks/upx"
  keywords = ["upx", "compression"]
  name = "Paketo Buildpack for UPX"
  sbom-formats = ["application/vnd.syft+json", "application/vnd.cyclonedx+json"]
  version = "{{.version}}"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/upx/blob/main/LICENSE"

[metadata]
  include-files = ["LICENSE", "NOTICE", "README.md", "buildpack.toml", "linux/amd64/bin/build", "linux/amd64/bin/detect", "linux/amd64/bin/run", "linux/arm64/bin/build", "linux/arm64/bin/detect", "linux/arm64/bin/run"]
  pre-package = "scripts/build.sh --target linux/amd64 --target linux/arm64"

  [[metadata.dependencies]]
    id = "upx"
    name = "UPX (The Ultimate Packer for eXecutables)"
    purl = "pkg:generic/upx@5.2.0?arch=amd64"
    sha256 = "3db5d3294707439db97866feab8d75d800f028f48481a40547411824da4288a1"
    source = "https://github.com/upx/upx/archive/refs/tags/v5.2.0.tar.gz"
    stacks = ["*"]
    uri = "https://github.com/upx/upx/releases/download/v5.2.0/upx-5.2.0-amd64_linux.tar.xz"
    version = "5.2.0"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0-or-later"
      uri = "https://github.com/upx/upx/blob/devel/LICENSE"

  [[metadata.dependencies]]
    arch = "amd64"
    checksum = "sha256:402162aad30af47e60dbd767fb2e64ca394ace9727ba1f40283641f1d1b91657"
    cpe = "cpe:2.3:a:upx_project:upx:5.2.1:*:*:*:*:*:*:*"
    id = "upx"
    name = "UPX (The Ultimate Packer for eXecutables)"
    os = "linux"
    purl = "pkg:generic/upx@5.2.1?arch=amd64"
    source = "https://github.com/upx/upx/archive/refs/tags/v5.2.1.tar.gz"
    source-checksum = "sha256:fb3dd4e9d6fe0bf774f71067696c08dfe10045af71d386cc54e8201b66e7e491"
    stacks = ["*"]
    uri = "https://github.com/upx/upx/releases/download/v5.2.1/upx-5.2.1-amd64_linux.tar.xz"
    version = "5.2.1"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0-or-later"
      uri = "https://github.com/upx/upx/blob/devel/LICENSE"

  [[metadata.dependencies]]
    arch = "arm64"
    checksum = "sha256:a72d112c5970a904a31da0b9c84f919bc16b9a311787c12245508544a78c7d36"
    cpe = "cpe:2.3:a:upx_project:upx:5.2.1:*:*:*:*:*:*:*"
    id = "upx"
    name = "UPX (The Ultimate Packer for eXecutables)"
    os = "linux"
    purl = "pkg:generic/upx@5.2.1?arch=arm64"
    source = "https://github.com/upx/upx/archive/refs/tags/v5.2.1.tar.gz"
    source-checksum = "sha256:fb3dd4e9d6fe0bf774f71067696c08dfe10045af71d386cc54e8201b66e7e491"
    stacks = ["*"]
    uri = "https://github.com/upx/upx/releases/download/v5.2.1/upx-5.2.1-arm64_linux.tar.xz"
    version = "5.2.1"

    [[metadata.dependencies.licenses]]
      type = "GPL-2.0-or-later"
      uri = "https://github.com/upx/upx/blob/devel/LICENSE"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "upx"
    patches = 2

[[stacks]]
  id = "*"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
